// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjPKnxAuCfvfLgaI4Zp3EXIw0nQg99uy8',
    appId: '1:204849947205:web:414e21106ec84c1903f92c',
    messagingSenderId: '204849947205',
    projectId: 'storied-deck-376821',
    authDomain: 'storied-deck-376821.firebaseapp.com',
    storageBucket: 'storied-deck-376821.appspot.com',
    measurementId: 'G-EN1QGRJH9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXPu_fZ5LixkBU-4ZeuemCki6YukRTH4',
    appId: '1:204849947205:android:a460966490d5192b03f92c',
    messagingSenderId: '204849947205',
    projectId: 'storied-deck-376821',
    storageBucket: 'storied-deck-376821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb5ZXT9WBpLTDmre_OaoC3uS8pw7kGuYA',
    appId: '1:204849947205:ios:e74a2d341cc60c2e03f92c',
    messagingSenderId: '204849947205',
    projectId: 'storied-deck-376821',
    storageBucket: 'storied-deck-376821.appspot.com',
    iosClientId: '204849947205-m91k0ahqd16gq18u4f5n975uomiehgaa.apps.googleusercontent.com',
    iosBundleId: 'dev.glebkoshcheev.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb5ZXT9WBpLTDmre_OaoC3uS8pw7kGuYA',
    appId: '1:204849947205:ios:e74a2d341cc60c2e03f92c',
    messagingSenderId: '204849947205',
    projectId: 'storied-deck-376821',
    storageBucket: 'storied-deck-376821.appspot.com',
    iosClientId: '204849947205-m91k0ahqd16gq18u4f5n975uomiehgaa.apps.googleusercontent.com',
    iosBundleId: 'dev.glebkoshcheev.myapp',
  );
}
